### ISSUE TITLE
Since update to windows 10 2004 mobswitcher no longer working

### ISSUE THREAD

**Issue by heedfull** [enorfelt/MobSwitcher#5]
When running mob command installed using chocolatey the following error is returned

An assembly specified in the application dependencies manifest (mob.dep.json) was not found:
  package: 'Microsoft.Extensions.Configuration.CommandLine', version: '3.1.1'
  path: 'lib/netcoreapp3.1/Microsoft.Extensions.Configuration.CommandLine.dll'

![image](https://user-images.githubusercontent.com/2331676/86758459-cb061b80-c03b-11ea-8c76-7b38c64caf7b.png)

**Comment by enorfelt** [comment]
Yes, I've seen this. Will look into it.

As a work around you can try to delete this folder: %temp%\\.net\mob
Then try run the mob command again.

**Comment by heedfull** [comment]
deleting from %temp%\.net\mob got it, working fine now

**Comment by enorfelt** [comment]
@heedfull version 1.3.4 is now available through Chocolatey.

choco upgrade mobswitcher

**Comment by heedfull** [comment]
Many thanks
